[tools]
go = "latest"
# `npm` must be placed before `node` not to use the npm provided by the Node.js installation.
npm = "latest"
node = "latest"
pnpm = "latest"
uv = "latest"
"pipx:mcp-server-time" = "latest"

[settings]
pipx_uvx = true
